### ISSUE TITLE
Build failed - undefined reference

### ISSUE THREAD

**Issue by TensorTom** [mhogomchungu/sirikali#120] opened 2019-09-22 19:26 UTC
followed build instructions on Manjaro (AUR version is outdated):
```
[ 17%] Linking CXX executable sirikali
/usr/bin/ld: /usr/lib/libKF5Wallet.so.5.61.0: undefined reference to `qt_version_tag@Qt_5.13'
/usr/bin/ld: /usr/lib/libKF5CoreAddons.so.5: undefined reference to `QString::arg(QLatin1String, int, QChar) const@Qt_5'
/usr/bin/ld: /usr/lib/libKF5Notifications.so.5.61.0: undefined reference to `QImage::sizeInBytes() const@Qt_5'
/usr/bin/ld: /usr/lib/libdbusmenu-qt5.so.2: undefined reference to `qt_version_tag@Qt_5.12'
/usr/bin/ld: /usr/lib/libKF5CoreAddons.so.5: undefined reference to `QMetaObject::invokeMethodImpl(QObject*, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, void*)@Qt_5'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sirikali.dir/build.make:1382: sirikali] Error 1
make[1]: *** [CMakeFiles/Makefile2:92: CMakeFiles/sirikali.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by mhogomchungu** [comment] 2019-09-22 19:31
I think the KDE libraries installed in your system have a dependency on old Qt version and the solutions here are:

1. Rebuild KDE to force it to pick up the updated Qt version.
2. Build SiriKali without KWallet support by passing the option ```-DNOKDESUPPORT=true``` to cmake.

**Comment by mhogomchungu** [comment] 2019-10-01 05:57
Closing this one the problem is local to your system and there is nothing i can do as upstream.

**Closed by mhogomchungu** 2019-10-01 05:57 UTC
