### ISSUE TITLE
Character set issues for gocryptfs password between Windows and Linux

### ISSUE THREAD

**Issue by Freeedim** [mhogomchungu/sirikali#124] opened 2019-10-18 15:00 UTC
Hi,

Thanks for the good work on SiriKali, which I like a lot.

Despite, I experienced an issue when trying to use the GUI to mount gocryptfs volumes with non-ASCII passwords.

When the GUI asks for the password to mount the volume, there is no problem for ASCII passwords but I have an error message "wrong password" when there are non ASCII characters.

The very same passwords do work when I use SiriKali command line with the option to enter my password in stdin and then paste the very same password when prompted to:

`john@myPC:~$ sirikali -d /media/MyDisk/MyVault -e -b "stdin" -z MyMountPoint -c /media/MyDisk/MyVault/gocryptfs.conf`
`Password: `
`john@myPC:~$ ls MyMountPoint`
`'My budget.xlsx'                 'My Presentation.pptx'`
`Archive.zip`

My passwords look like this: ‼ꝦꝞ♂í9╟⅜ᴚՉₐῺԔՉ®ƵᾞἜẤᴓֆꞠʅѨЗͲɾꜤȗ
The volume was created with cppcryptfs under Windows 10. The password was created in UTF-8 with Notepad++, then pasted in cppcryptfs's GUI when creating the volume.

In Windows with cppcryptfs, the password works when pasted in the GUI and when read from the UTF-8 file by a BAT script (which first switches the CMD environment to UTF-8 with the command "CP 65001").

In Linux, ASCII passwords work on both the GUI and command line but non-ASCII passwords only work in the command line (copied from a UTF-8 file and pasted in the terminal when the password is asked).

I run KDE on a Debian, with French locale. But I switched to "en_US" locale/keyboard and the problem remained.

What do you think?

Cheers!

**Comment by mhogomchungu** [comment] 2019-10-19 06:40
Put the password in a file and send the file to me using my email address of mhogomchungu@gmail.com

I cant be certain i am using the right password when copying it from here and then start using it.

It would also be better if could send a gocryptfs config file created with the password.

**Comment by Freeedim** [comment] 2019-10-19 22:12
Hi,
Thanks for your quick answer.
I did it but forgot to write the versions:
SiriKali 1.4.0 (compiled with Qt)
gocryptfs 1.7

**Comment by mhogomchungu** [comment] 2019-10-20 02:12
I can reproduce the issue.

QString, a Qt class SiriKali is using to carry the password around the code can't handle that password string by default.

I will be travelling in a few hours from now and I won't be able to work on this until about 7 days have passes from today.

**Comment by Freeedim** [comment] 2019-10-20 12:48
Good to know you could spot the problem.
I usually prefer to use SiriKali though command lines, so I am not in hurry. The GUI is just more practical for vaults initial setup and tests...
Cheers and travel safe!

**Comment by mhogomchungu** [comment] 2019-10-25 22:02
The problem is now fixed.

The problem was caused by SiriKali using QString::toLatin1()[1] instead of QString::toUtf8[2] when it was reading the password from the UI.

[1] https://doc.qt.io/qt-5/qstring.html#toLatin1
[2] https://doc.qt.io/qt-5/qstring.html#toUtf8

**Closed by mhogomchungu** 2019-10-25 22:02 UTC

**Comment by Freeedim** [comment] 2019-10-26 07:18
Thanks a lot for your quick response.

I think it will be perfect for me since I only work in UTF-8. But don't you fear that it will break something for other people?

I did some effort and used Notepad++ (under Windows) to have my passwords in UTF-8 while creating the encrypted volumes with cppcryptfs/Windows (Windows is not natively prone to UTF-8). Maybe some other people who create volumes with cppcryptfs/Windows without paying attention (e.g. in latin1 charset) will now have hard time mounting their volumes with SiriKali GUI.
(Sorry I am not a programmer and I don't really know if my concerns make sense).

**Comment by mhogomchungu** [comment] 2019-10-26 07:44
My understanding says that all latin-1 characters are valid utf8 characters but some utf8 characters are not valid latin-1 character and the problem was here. When Qt encounters a non valid latin-1 character, it either drops it or replace it with "?" character.

This change will not affect users who use passwords with only latin-1 characters.

Yes, this is a breaking change for those who created volumes using SiriKali with passwords that contain non-Latin1 characters because the effective password in use is "undefined" according Qt documentation.

I think the best thing to do is to keep the new behavior and force users to change the volume password.

I will add some sort of a warning to inform users when their old password no longer work because of this change.
