### ISSUE TITLE
Building for Mac OS

### ISSUE THREAD

**Issue by marc-git** [mhogomchungu/sirikali#147] opened 2020-05-14 14:02 UTC
Just FYI, following the instructions provided I get the following error:
```

[ 13%] Building CXX object src/3rdParty/lxqt_wallet/frontend/CMakeFiles/lxqt-wallet.dir/moc_password_dialog.cpp.o
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
/Users/mmmm/software/sirikali/src/3rdParty/lxqt_wallet/frontend/lxqt_windows_dpapi.cpp:307:14: error: 
      use of undeclared identifier 'TEST_VALUE'
        if( test != TEST_VALUE ){
                    ^
/Users/mmmm/software/sirikali/src/3rdParty/lxqt_wallet/frontend/lxqt_windows_dpapi.cpp:352:23: error: 
      use of undeclared identifier 'TEST_VALUE'
        std::memcpy( buffer,&TEST_VALUE,int_size ) ;
                             ^

```

**Comment by mhogomchungu** [comment] 2020-05-14 17:28
Update from git and try again.

Closing it because the issue is now resolved but feel free to comment if anything else comes up.

**Closed by mhogomchungu** 2020-05-14 17:28 UTC
