### ISSUE TITLE
sirikali 1.4.2 wont decrypt cryfs after moving from linux mint 19 --> 20

### ISSUE THREAD

**Issue by astrale-sharp** [mhogomchungu/sirikali#157] opened 2020-07-23 17:53 UTC
when you try to decrypt on a pre update volume, it says it needs to update the filesystem of the volume, you try again it then says its gonna take a long time to decrypt a cryfs volume, then when it tries infinitly (once waited 40minutes),
before upgrading my OS this action took 5-6 min

note that .Sirikali/yourVolumeName stays empty

i realize i dont have the latest version, im going to build it and try again

**Comment by astrale-sharp** [comment] 2020-07-23 18:08
also, for it says one of my password is wrong, when im 99% sure it isnt.. i hope this is a fixable problem! i have pretty serious data not backed up :((((

**Comment by mhogomchungu** [comment] 2020-07-23 18:35
CryFS is known for being picky on what version of its file system can be opened with what version of CryFS.

1. What version of CryFS is in mint 19.
2. What version of CryFS is in mint 20.

Some versions of CryFS can unlock and migrate some older versions of its file systems that were created with older versions of CryFS and SiriKali can assist in doing the migration and some versions of its older file systems can not be migrated by newer versions of CryFS.

Best thing to do is to run CryFS from the terminal in an interactive mode and see what it says and see if you manually do the migration.

If you can't do the migration then you have two alternatives.

1. Install the version of CryFS that is in mint 19 in mint 20 and use it, effectively stopping updating CryFS.
2. Install both versions of CryFS and then create a new volume with the version in mint 20 and then unlock the volume with version in mint 19 and copy files over.

**Comment by astrale-sharp** [comment] 2020-07-23 18:52
im a bit reassured !
i'll do that
"""
    What version of CryFS is in mint 19.
    What version of CryFS is in mint 20.
"""

do you think building the latest version of sirikali is a good idea? the package on mint 20 is 1.4.2 (via sudo apt install sirikali)

**Comment by mhogomchungu** [comment] 2020-07-23 19:07
Versions of SiriKali will not make a difference so continue with the 1.4.2 version.

**Comment by mhogomchungu** [comment] 2020-08-01 19:30
Closing this one since the problem is with CryFS and is outside of SiriKali's control.

**Closed by mhogomchungu** 2020-08-01 19:30 UTC
