### ISSUE TITLE
hidden crypt folders cannot be made favorites

### ISSUE THREAD

**Issue by sm8ps** [mhogomchungu/sirikali#115] opened 2019-09-02 19:23 UTC
Stepped into some kind of edge case here. My Encfs-encrypted folder is hidden, i.e. its name starts with a dot like '.hiddenFolder'. I have tried several times to add it as a favourite but the GUI remains blank after putting in the relevant information. I was convinced that SiriKali was broken.

After a while, I found several entries in '~/.config/SiriKali/favorites/' named like '.hiddenFolder-####.json' where "####" stands for some token. Renaming one of them to 'hiddenFolder-####.json', i.e. removing the leading dot from its name, made it appear as a favourite in the GUI. Which is fine for a first use.

Afterwards, however, it is not possible to change any of the options through the GUI because the JSON-file will again be saved with a leading dot in its name, thereby losing it. As a work-around, one may fiddle with the contents of that file directly.

If memory serves me well this had not been a problem up to now. I had SiriKali working just fine until I upgraded and rebooted the machine today. Was there a change in a recent version that made the program disregard hidden files in its favourites folder?

This happened with SiriKali 1.3.9 on Ubuntu 19.04. The Apt-logs show a recent upgrade from version 1.3.8 about two weeks ago and it appears from the system logs that I have not rebooted the machine until today.

**Comment by mhogomchungu** [comment] 2019-09-03 07:39
The problem is fixed in git with this[1] commit.

Old versions of SiriKali stored favorites entries as an entry in the application's configuration file and this was a bit limiting.

Newer versions stores favorites entries in json files and each favorite entry is stored in its own file on the file system. The problem was the Qt API i use to read favorites entries from the file system does not automatically include hidden files and the fix is to instruct the API to include them.

The token is there to uniquely identify a ```cipher path+mount point``` combination because some people want to have the same cipher path using different mount points.

[1] https://github.com/mhogomchungu/sirikali/commit/6c62ef6b6d1a1a124c5a8d51bb033fe77586a07d

**Closed by mhogomchungu** 2019-09-03 07:39 UTC

**Comment by sm8ps** [comment] 2019-09-03 08:28
Great! Thanks for the quick fixing and the explanation as well! Shall quickly report back after testing the new version from the PPA.

**Comment by sm8ps** [comment] 2019-09-04 04:14
Working well with version 1.3.9.1567495760.6c62ef6-0 from the Ubuntu 19.04 PPA. Respects for the quick reaction!

**Comment by guillaume-uH57J9** [comment] 2019-10-05 11:54
Thanks for the fix! I got affected by this as well.
