### ISSUE TITLE
File size limitations

### ISSUE THREAD

**Issue by IsaakGroepT** [mhogomchungu/sirikali#96] opened 2019-04-17 18:10 UTC
Hi

Do you (implicitly) impose file size limitation for gocryptfs containers? For some reason I can't move a file of +1.1GB to my container. It raises a "there's not enough free space error", while the disk has plenty left.

I didn't find any such restriction documented anywhere though

**Comment by mhogomchungu** [comment] 2019-04-17 18:46
SiriKali does not add any limitations to its backend and SiriKali can not be the source of the problem.

Best thing to do is to run gocryptfs from the terminal and reproduce the issue before reporting it at gocryptfs bug tracker.

In your bug report, you should report what version of gocryptfs you are using and what file system the encrypted container folder lives in. Fat32 file system for example has a maximum file size of 4GB and i dont think gocryptfs works around this.

**Comment by IsaakGroepT** [comment] 2019-04-17 19:13
Thanks for the info, but I think Sirikali handles the mounts in its own way because I use HMAC-Keyfile instead of a password and I don't see such an option with gocryptfs. How does sirikali calculate that passphrase in that situation?

**Comment by mhogomchungu** [comment] 2019-04-17 19:39
in "HMAC-Keyfile" mode, SiriKali takes the keyfile and generates an hmac hash using sha256 and an empty password.

You can get the key SiriKali sends to gocrypt by clicking the checkbox next to the password field as seen in the below image

You can also calculate the hash independently of SiriKali by using ```hmac256``` tool and the command to use is ```hmac256 "" /path/to/your/keyfile```


![Screenshot_20190417_223117](https://user-images.githubusercontent.com/3496115/56315809-5c505000-6161-11e9-9ceb-29f83ff444d4.png)

**Comment by mhogomchungu** [comment] 2019-04-18 15:49
Closing this one since the issue is with upstream.

**Closed by mhogomchungu** 2019-04-18 15:49 UTC
