### ISSUE TITLE
Password format support

### ISSUE THREAD

**Issue by BrsyRockSs** [mhogomchungu/sirikali#200] opened 2022-02-04 17:51 UTC
Password format support
When using securefs encryption, when the password is other than numbers and letters, it cannot be mounted normally with sirikali, and it prompts that the password is wrong. When mounting with cmd, it can be mounted normally. Can you support passwords with complex characters ?
Example:
o(4w法cJ傲>9计计C2+5DwvPUpc骄]]Mj}T_2六卡骄9=骄打d/六ALVb5{5P

**Comment by mhogomchungu** [comment] 2022-02-04 21:35
1. How did you create this volume?
2. Are you sure CMD is not messing with your password?

Close SiriKali, go the registry editor and then toggle highlighted option and see if it makes a difference.

![Screenshot_20220205_003239](https://user-images.githubusercontent.com/3496115/152606171-7e194799-a1b6-4f74-9fe1-9392b3c4f758.png)

**Comment by BrsyRockSs** [comment] 2022-02-05 03:11
Hello!

Thank you for your reply. I'll answer your question first

1. Because the default value of "full" format in the creation of encrypted volume provided by SK itself is 2, and what I need is 3, I create the encrypted volume in CMD with the following command
>securefs create "C:/Users/brsyr/Desktop/test_01" --format 3
Then copy the password, right-click and enter it into CMD to complete the creation
2. I reconfirmed that CMD can unlock the disk normally
3. Switching `passwordisutf8encoded` does not solve the problem
----
Sorry, I forgot to provide you with the following information. When using the software itself to create an encrypted disk, using special characters does not seem to trigger this problem
But this problem happens when I use format 3
![屏幕截图 2022-02-05 111048](https://user-images.githubusercontent.com/46119880/152626771-4deaffba-494f-4eb5-8f50-adca4a16c2b9.png)

**Comment by mhogomchungu** [comment] 2022-03-01 09:26
Sorry for a late reply, i somehow lost track of this one.

My conclusion is that CMD is messing with your password and try to unlock that folder anywhere else and it will also fail.

I did an experiment here by creating a securefs volume on my linux system using your password from the terminal and SiriKali successfully unlocked it.

I transferred the volume to windows 10 and SiriKali opened it.
I tried to unlock the volume using CMD and it failed.
I tried to unlock the volume using git bash and it worked.

A volume create with CMD using that password also failed to unlock using git bash and vice versa.

See the image below that shows CMD failing while git bash worked.

![Screenshot_20220301_121644](https://user-images.githubusercontent.com/3496115/156141316-332d9496-d32e-4377-9ca3-cf3d8c9a46de.png)

**Comment by mhogomchungu** [comment] 2022-03-01 10:50
Found the solution, below command creates a volume using CMD and SiriKali can open it

```
securefs.exe create uuu --pass "o(4w法cJ傲>9计计C2+5DwvPUpc骄]]Mj}T_2六卡骄9=骄打d/六ALVb5{5P"
```

When mounting it using CMD, you also have to pass the password through --pass option like below:-

```
securefs.exe mount uuu W: --pass "o(4w法cJ傲>9计计C2+5DwvPUpc骄]]Mj}T_2六卡骄9=骄打d/六ALVb5{5P"
```

So the problem is with how securefs reads the password from stdin.

**Comment by BrsyRockSs** [comment] 2022-03-04 05:48
Thank you for answering my questions and for the software you coded,
I wish you happiness every day, thank you

**Closed** 2022-03-04 05:48 UTC
