### ISSUE TITLE
Cannot remount a volume after shutdown - folder already present

### ISSUE THREAD

**Issue by banditopazzo** [mhogomchungu/sirikali#68] opened 2018-07-08 15:10 UTC
Hi, I have encountered this issue with favorites, I'm on Linux (Arch 64) using gocryptfs volume. 

When I shutdown or reboot my PC without unmount a drive, on the next boot SiriKali won't be able to mount again the volume.
This is because on shutdown it doesn't delete the folder where the drive was mounted. If I manually delete the empty folder and try to mount the volume manually or open again SiriKali with automount it works.

**Comment by mhogomchungu** [comment] 2018-07-08 15:16
It is expected behavior, by default, SiriKali wants exclusive control of the mount point path and it will complain if it finds the path  to already be occupied when mounting and will automatically delete the mount folder after unmounting.

If you want SiriKali to reusing an already existing mount point with a consequence of SiriKali not deleting it after unmounting, set "re use mount point" option located at menu->settings->general options->re use mount point

**Comment by mhogomchungu** [comment] 2018-07-08 16:01
SiriKali is intentionally designed on linux and macos to exit while a volume is still mounted. It doesnt work this way on windows due limitations of its backends.

Will look into trying to unmount volumes when a use logs out/shutdown the system while SiriKali is running and has open volumes.

Closing this one since reported issues has been solved.

**Closed by mhogomchungu** 2018-07-08 16:01 UTC

**Comment by mhogomchungu** [comment] 2018-11-06 16:48
I just implementing a feature that causes SiriKali on Linux to unmount all volumes and quit when it receives sigterm and sighup signals and it should therefore unmount all volume when a user logs out IF the DE sends one of these signals to notify all running applications of the impending login out..

**Comment by banditopazzo** [comment] 2018-11-14 10:42
great!!

**Comment by Alt37** [comment] 2021-01-11 01:41
@mhogomchungu 
I have very similar problem with KDE Plasma 5.18 (didn't check others yet) & Cryptomator
SiriKali.conf has
`UnMountVolumesOnLogout=true`
But when I logout from system, volume remains mounted.
For now I execute script at logout:
`mount -l | grep Cryptomator@ | awk -F " " '{print "fusermount -u " $3; print "rm -d " $3}' | bash`
"rm -d" deletes only empty folders so it's probably safe. It also unmounts volumes unknown for a new copy of SiriKali if previous one(s) crashed/killed.

**Comment by mhogomchungu** [comment] 2021-01-11 18:47
What desktop environment are you using?

1. Start SiriKali and then unlock a cryptomator volume.
2. Send SiriKali SIGTERM or SIGHUP and report if it unmounts the volume and quit or not.
