### ISSUE TITLE
no longer able to connect to sshfs volumes

### ISSUE THREAD

**Issue by fabeit** [mhogomchungu/sirikali#175] opened 2020-12-17 15:06 UTC
I don't know what's happening but I am no longer able to connect to my volumes, I can connect fine with WinSCP so it's not a problem on the server-side. I have the same problem on two separate servers, so I'm quite sure it's not a problem with the server.

The only thing I can remember changing is doing some Windows updates to .NET framework, but this should not conflict with Sirikali. I have this problem with the  1.4.7 and with the 1.4.8 versions.

This is the message I get

Failed To Complete The Task And Below Log was Generated By The Backend.

----------------------------------------
ssh: Could not resolve hostname ssh1.xxx.xxx.com: Name or service not known
read: Connection reset by peer

**Comment by mhogomchungu** [comment] 2020-12-17 15:37
While SiriKali main window has focus, press CTRL+D to bring up debug window and then try to connect again and post the command SiriKali send to sshfs-win. Dont forget to hide your server's IP address.

What command are you running when connecting with "WinSCP"? again, dont forget to hide the server's IP address.

**Comment by fabeit** [comment] 2020-12-17 15:41
1. Processing favorite entry: sshfs fberzagh@ssh1.lsce.ipsl.fr:/home/users/fberzagh/
2. Favorite entry does not have a password
3. Trying to get password from wallet for path: sshfs user@xxx:/home/
3.1 Retrying to get password from wallet for path: sshfs user@xxx:/home/
4. Favorite entry does not exist in the wallet
*************************************
Command: "C:\Program Files\SSHFS-Win\\\bin\sshfs.exe" "-o" "reconnect" "-f" "user@xxx:/home/" "T:" "-o" "rw,fsname=Sshfs@fberzagh@ssh1.lsce.ipsl.fr:/home/users/fberzagh/,subtype=Sshfs,ServerAliveInterval=15,idmap=user,StrictHostKeyChecking=no,volname=user,PreferredAuthentications=password,password_stdin"
*************************************
warning, a process is no longer running
*************************************
*************************************
Backend took 4 seconds to unlock a volume
*************************************
*************************************
Process Finished
*************************************
-------
Exit Code: -1
Exit Status: 0
-------
StdOut:
ssh: Could not resolve hostname ssh1.xxxx: Name or service not known
read: Connection reset by peer
-------
StdError:
*************************************

**Comment by fabeit** [comment] 2020-12-17 15:47
This is the log from winscp

. 2020-12-17 16:44:12.178 --------------------------------------------------------------------------
. 2020-12-17 16:44:12.179 WinSCP Version 5.17.3 (Build 10325) (OS 10.0.18363 - Windows 10 Enterprise)
. 2020-12-17 16:44:12.179 Configuration: HKCU\Software\Martin Prikryl\WinSCP 2\
. 2020-12-17 16:44:12.179 Log level: Normal
. 2020-12-17 16:44:12.179 Process ID: 2628
. 2020-12-17 16:44:12.181 Command-line: "C:\Program Files (x86)\WinSCP\WinSCP.exe" 
. 2020-12-17 16:44:12.182 --------------------------------------------------------------------------
. 2020-12-17 16:44:12.182 Session name: home (Site)
. 2020-12-17 16:44:12.182 Host name: xxx (Port: 22)
. 2020-12-17 16:44:12.182 User name: user (Password: Yes, Key file: No, Passphrase: No)
. 2020-12-17 16:44:12.182 Tunnel: No
. 2020-12-17 16:44:12.182 Transfer Protocol: SFTP (SCP)
. 2020-12-17 16:44:12.182 Ping type: Dummy, Ping interval: 30 sec; Timeout: 15 sec
. 2020-12-17 16:44:12.182 Disable Nagle: No
. 2020-12-17 16:44:12.182 Proxy: None
. 2020-12-17 16:44:12.182 Send buffer: 262144
. 2020-12-17 16:44:12.182 SSH protocol version: 2; Compression: No
. 2020-12-17 16:44:12.182 Bypass authentication: No
. 2020-12-17 16:44:12.182 Try agent: Yes; Agent forwarding: No; TIS/CryptoCard: No; KI: Yes; GSSAPI: Yes
. 2020-12-17 16:44:12.182 GSSAPI: Forwarding: No; Libs: gssapi32,sspi,custom; Custom: 
. 2020-12-17 16:44:12.182 Ciphers: aes,chacha20,blowfish,3des,WARN,arcfour,des; Ssh2DES: No
. 2020-12-17 16:44:12.182 KEX: ecdh,dh-gex-sha1,dh-group14-sha1,rsa,WARN,dh-group1-sha1
. 2020-12-17 16:44:12.183 SSH Bugs: Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto
. 2020-12-17 16:44:12.183 Simple channel: Yes
. 2020-12-17 16:44:12.183 Return code variable: Autodetect; Lookup user groups: Auto
. 2020-12-17 16:44:12.183 Shell: default
. 2020-12-17 16:44:12.183 EOL: LF, UTF: Auto
. 2020-12-17 16:44:12.183 Clear aliases: Yes, Unset nat.vars: Yes, Resolve symlinks: Yes; Follow directory symlinks: No
. 2020-12-17 16:44:12.183 LS: ls -la, Ign LS warn: Yes, Scp1 Comp: No; Exit code 1 is error: No
. 2020-12-17 16:44:12.183 SFTP Bugs: Auto,Auto
. 2020-12-17 16:44:12.183 SFTP Server: default
. 2020-12-17 16:44:12.183 Cache directory changes: Yes, Permanent: Yes
. 2020-12-17 16:44:12.183 Recycle bin: Delete to: No, Overwritten to: No, Bin path: 
. 2020-12-17 16:44:12.183 DST mode: Unix
. 2020-12-17 16:44:12.183 --------------------------------------------------------------------------
. 2020-12-17 16:44:12.273 Looking up host "xxx" for SSH connection
. 2020-12-17 16:44:12.311 Connecting to xxx.xxx.xx.xx port 22
. 2020-12-17 16:44:12.353 We claim version: SSH-2.0-WinSCP_release_5.17.3
. 2020-12-17 16:44:12.382 Remote version: SSH-2.0-OpenSSH_7.4
. 2020-12-17 16:44:12.382 Using SSH protocol version 2
. 2020-12-17 16:44:12.385 No GSSAPI security context available
. 2020-12-17 16:44:12.385 Have a known host key of type ssh-ed25519
. 2020-12-17 16:44:12.414 Doing ECDH key exchange with curve Curve25519 and hash SHA-256
. 2020-12-17 16:44:12.568 Server also has ecdsa-sha2-nistp256/ssh-rsa host keys, but we don't know any of them
. 2020-12-17 16:44:12.568 Host key fingerprint is:
. 2020-12-17 16:44:12.568 ssh-ed25519 255 0e:bb:ec:aa:8b:7e:ba:9e:42:0f:d7:a5:5e:34:cc:45 7pjG/wA9j+workxqcuRdg3nLev0OuRgDnGRldzQe9UY=
. 2020-12-17 16:44:12.609 Host key matches cached key
. 2020-12-17 16:44:12.609 Initialised AES-256 SDCTR (AES-NI accelerated) outbound encryption
. 2020-12-17 16:44:12.609 Initialised HMAC-SHA-256 outbound MAC algorithm
. 2020-12-17 16:44:12.609 Initialised AES-256 SDCTR (AES-NI accelerated) inbound encryption
. 2020-12-17 16:44:12.609 Initialised HMAC-SHA-256 inbound MAC algorithm
! 2020-12-17 16:44:12.636 Using username "user".
. 2020-12-17 16:44:12.699 Server offered these authentication methods: publickey,gssapi-keyex,gssapi-with-mic,password
. 2020-12-17 16:44:12.699 Using SSPI from SECUR32.DLL
. 2020-12-17 16:44:12.699 Trying gssapi-with-mic...
. 2020-12-17 16:44:12.699 Attempting GSSAPI authentication
. 2020-12-17 16:44:12.728 GSSAPI authentication request refused
. 2020-12-17 16:44:12.728 Server offered these authentication methods: publickey,gssapi-keyex,gssapi-with-mic,password
. 2020-12-17 16:44:12.728 Prompt (password, "SSH password", <no instructions>, "&Password: ")
. 2020-12-17 16:44:12.728 Using stored password.
. 2020-12-17 16:44:12.759 Sent password
. 2020-12-17 16:44:12.914 Access granted
. 2020-12-17 16:44:12.915 Opening main session channel
. 2020-12-17 16:44:13.048 Opened main channel
. 2020-12-17 16:44:13.081 Started a shell/command

**Comment by mhogomchungu** [comment] 2020-12-17 17:02
I do not see anything wrong with what SiriKali is doing.

1. Remove the "reconnect" option and try again.
2. Look at logs on the server side, do they say anything when connecting using sshfs-win+SiriKali

**Comment by mhogomchungu** [comment] 2020-12-18 09:46
The problem may be caused by firewall: https://winscp.net/eng/docs/faq_connection_refused

**Comment by fabeit** [comment] 2020-12-18 11:40
I have worked with my sys administrator and we found the cause, Sirikali cannot resolve the address to the IP, so I substituted the URL with the IP and now it works again. This is very strange because if I do

nslookup myserver.com the IP is resolved.

**Comment by mhogomchungu** [comment] 2020-12-18 12:17
I am glad the problem is solved.

The reported error message was a bit contradicting.

The first line(Could not resolve hostname) suggested the client could not reach the server and the second line(Connection reset by peer) suggested the server was closing the connection because it didn't like something from the client.

**Closed by mhogomchungu** 2020-12-18 12:17 UTC
