### ISSUE TITLE
SSH_AUTH_SOCK Field no longer available?

### ISSUE THREAD

**Issue by Veggies** [mhogomchungu/sirikali#163] opened 2020-09-04 22:45 UTC
In the wiki it states

> SSH_AUTH_SOCK environmental variables should be added to the SSH_AUTH_SOCK Socket Path field if its necessary.

However on the latest release, this field is no longer visible, or no longer exists. Is there a way to re implement this field?

**Comment by mhogomchungu** [comment] 2020-09-05 05:55
What OS are you using and are you sure you are talking about the text field in the image below?

![ssh](https://user-images.githubusercontent.com/3496115/92298820-642ab300-ef55-11ea-9922-29bffc307481.png)

**Comment by Veggies** [comment] 2020-09-05 06:58
> What OS are you using and are you sure you are talking about the text field in the image below?
> 
> ![ssh](https://user-images.githubusercontent.com/3496115/92298820-642ab300-ef55-11ea-9922-29bffc307481.png)

Yes I am referencing this field. I am on windows 10. That field does not exist on the program in windows.

**Comment by mhogomchungu** [comment] 2020-09-05 07:13
It does in mine, are you sure you are using version 1.4.6? Post your screenshot.

![ssh](https://user-images.githubusercontent.com/3496115/92300032-53cc0580-ef60-11ea-9ee3-6a9107806b9a.png)

**Comment by Veggies** [comment] 2020-09-05 07:17
This is very strange. I am one 1.4.6, however many of the options on your version are definitely different that mine.
![weird](https://user-images.githubusercontent.com/6461840/92300117-5136d380-ef93-11ea-9af3-19f9965cfcb8.png)

**Comment by Veggies** [comment] 2020-09-05 07:24
Hey I figured the issue. The SSH sock may only be modified/pointed to during initial creation of the volume link, it cannot be edited in later. I am not very familiar with these things, however it would make sense to me to have this field be editable on a pre-existing mount/favorite no?

**Comment by mhogomchungu** [comment] 2020-09-05 07:45
Yes, this is a bug, when modifying sshfs settings, the GUI should be for sshfs settings and not for other supported backends.

If you set the SSH_AUTH_SOCK option, it will show up in the mount options field as "IdentityAgent" and you can change it from here.

![ssh](https://user-images.githubusercontent.com/3496115/92300501-f1750400-ef63-11ea-9e87-817abccd5bb7.png)

**Comment by mhogomchungu** [comment] 2020-09-05 08:17
One thing to note here is that there is a fundamental problem here.

SiriKali supports multiple programs and they can be grouped in two groups.

1. Program that use ssh.
2. Programs that do not.

The current default behavior for SiriKali is for programs that are in the second group and someone who uses SiriKali only for sshfs will see quite a bit of behaviors and texts that are odd like "unlocking" instead of "connecting".

Support for programs in group 1 were added last and the bug here is due to attempting to reusing existing GUI elements for programs that are very different.

**Comment by mhogomchungu** [comment] 2020-09-05 19:31
The issue is fixed in the git version. Image 1 below shows text changing to appropriate sshfs config options when selecting sshfs entry in the favorites list and image 2 below shows appropriate sshfs config options in the add/edit favorite's tab. If you get to the add/edit favorites tab and you don't see sshfs options text, then click the button pointed by the right arrow and select "sshfs" on the produced list.

Next version will be released in Nov 1st, 2020.

Image 1
![ssh1](https://user-images.githubusercontent.com/3496115/92312084-4d707480-efc6-11ea-89f0-2eb367ef4634.png)

image 2
![ssh2](https://user-images.githubusercontent.com/3496115/92312094-55c8af80-efc6-11ea-8d13-f27387adad5d.png)

**Closed by mhogomchungu** 2020-09-05 19:31 UTC

**Comment by mhogomchungu** [comment] 2020-10-01 06:20
New version is out and i recommend you update to it: https://github.com/mhogomchungu/sirikali/releases/tag/1.4.7
