### ISSUE TITLE
Crashes on Windows 10 and won't run (SSHFS)

### ISSUE THREAD

**Issue by jwhipp** [mhogomchungu/sirikali#129] opened 2019-11-11 17:49 UTC
I installed Sirikali using the setup exe download option.  Installed and ran just fine, so I attempted to mount an SSHFS volume using the gui and it crashed.  Now I can't git it to run at all.

From Windows logs, I see this:

Faulting application name: sirikali.exe, version: 0.0.0.0, time stamp: 0x5da5bf49
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x40000015
Fault offset: 0x0002085d
Faulting process id: 0x36b8
Faulting application start time: 0x01d598b7ce03c4ae
Faulting application path: C:\Program Files (x86)\SiriKali\sirikali.exe
Faulting module path: C:\Program Files (x86)\SiriKali\libstdc++-6.dll
Report Id: fd15c197-2b9c-414c-9ac2-8fec6aaf6456
Faulting package full name: 
Faulting package-relative application ID:

**Comment by jwhipp** [comment] 2019-11-11 17:57
Update... if I nuke AppData\Local\Sirikali it runs once more.

**Comment by mhogomchungu** [comment] 2019-11-11 18:23
I have never seen a crash here. You should have sent me the contents of the folder so that i can look at it. 

The crash was probably due to SiriKali failing to parse a json file that hold information about your sshfs favorite's entry.

**Comment by mhogomchungu** [comment] 2019-11-12 06:19
I think the crash was caused by an uncaught exception and i fixed it here[1]. The exception was raised by an external project that parses json files and i cant think of a reason why it raised the exception.

Closing this one since i think i have solved the crash but would appreciate if you could recreate the problematic file and send it to me.

[1] https://github.com/mhogomchungu/sirikali/commit/0836ed0a1a25b150715f6b27b587e37d5a20810c#diff-e7b869b74817bd4067a3f8dc981327df

**Closed by mhogomchungu** 2019-11-12 06:19 UTC

**Comment by mhogomchungu** [comment] 2019-11-18 14:58
Found the solution to the problem you reported here[1]. The below link has a link to a binary application you can use to work around the problem.

https://github.com/mhogomchungu/sirikali/issues/130

**Comment by mhogomchungu** [comment] 2019-12-18 04:36
New version is out and it has a fix for this crash

https://github.com/mhogomchungu/sirikali/releases/tag/1.4.2
