### ISSUE TITLE
macOS: changing file manager

### ISSUE THREAD

**Issue by eugenesvk** [mhogomchungu/sirikali#38] opened 2017-09-02 03:42 UTC
What format should I use in the settings to replace Finder with Path Finder?
If I use just the application name with its path, Sirikali opens a new instance of Path Finder (rather weird, first time I see another instance of an app launched instead of opening an already running application), if I use `/usr/bin/open "/Applications/Path Finder.app"` (as e.g. `/usr/bin/open "/Applications/Path Finder.app" ~` from the terminal would open `~` Home Path in Path Finder), hoping Sirikali would add path to the new volume, it doesn't work either.

**Comment by mhogomchungu** [comment] 2017-09-02 08:48
I do not have a Mac, I have never used a Mac and i know nothing about
macintosh computers. All the Mac support in SikiKali comes from Mac users
making feature requests and testing the functionality I blindly code.

You will have to figure this one yourself and if there is something that
needs to be done on my end, tell me and I will do it but you will have to
test it.

Alternatively, another Mac user will come along and help us out with this
issue.

**Comment by eugenesvk** [comment] 2017-09-02 09:40
Ok, how do you launch Finder at the moment and how do you pass current path to Finder on volume mount? And what do you do with the command user enters in the settings (how do you launch that vs the default Finder)?

**Comment by mhogomchungu** [comment] 2017-09-02 09:56
At the moment, Sirikali issues a command that looks like "/use/bin/open /path/to/mount/folder. 

There is a GUI config option to change the command to something else. The solution to your problem is probably to configure " open" command to use "path finder " as it's default file manager.

Look up "path finder" documentation to see if it has options you can use to make it reuse an existing window.

**Comment by mhogomchungu** [comment] 2017-09-02 10:12
Sorry, I am on mobile and I pressed the wrong button. To clarify, sirikali uses "open" command on osx and it has no idea what file manager will end up being used.

Sirikali has a GUI option to replace "open" tool with another one.

If you want yo use "path finder" tool to open folder paths, look up its documentation on how it can be invoked in a way that reused the same file manager instance and use the command with the option on sirikali.

**Comment by eugenesvk** [comment] 2017-09-02 11:02
Well, as I mentioned above, `/usr/bin/open "/Applications/Path Finder.app" /Path/To/Mount/Folder` works just fine, so if you're currently using `/use/bin/open /path/to/mount/folder` can you not just insert the user defined value from that GUI option?
The issue seems to be that the **/path/to/mount** is not properly passed to the user command. For example, if I just set `/usr/bin/open "/Applications/Path Finder.app" /Applications/` then on volume mount I get a new tab in **Path Finder** with **Applications** folder opened. But that means Sirikali didn't pass any path (otherwise there should've been an error)

**Comment by mhogomchungu** [comment] 2017-09-03 09:42
SiriKali was designed with only two arguments when it comes to opening a mounted folder,a program to open the mount point and a path to the mount point. 

Your usecase wants three argument and try the following to see if it will work,click menu->set file manager and in the window,add the following line and see if it will work.

```
/usr/bin/open ''"/Applications/Path Finder.app"'''
```

Note sure why open behaves differently in SiriKali.

**Comment by eugenesvk** [comment] 2017-09-03 18:04
This doesn't work, but good news is that I don't have Finder being launched now either :)
And when I try to manually open a mounted drive, I get the error that this "tool does not appear to be working properly"

**Comment by mhogomchungu** [comment] 2017-09-05 12:57
Try this workaround,create a script with below content,make it executable and set SiriKali to use it and see if it helps.

This script will act as a bridge since it will allow SiriKali to use two arguments while OSX will see three since the script secretly adds the middle argument.

```
#!/bin/bash

/usr/bin/open "/Applications/Path Finder.app" $1
```

**Comment by eugenesvk** [comment] 2017-09-05 18:15
I still have SiriKali open Path Finder, but open the actual path in Finder :(

**Comment by mhogomchungu** [comment] 2018-04-13 17:26
Closing this one for luck of activity.

I will have to sit in front of a MACOS computer to figure this one out and i dont see myself doing that anytime soon.

**Closed by mhogomchungu** 2018-04-13 17:26 UTC

**Comment by eugenesvk** [comment] 2022-12-23 17:15
By the way, this script seems to be working

`sirikali-open.sh`
```sh
#!/bin/bash
/usr/bin/open -b 'com.cocoatech.PathFinder' $1
```

Then just set `/~/path/to/sirikali-open.sh` in the settings (might need to restart the app for it to start working)
